### ISSUE TITLE
Hot mode and separate entities for controlling power on power off, temperature, modes etc are not available

### ISSUE THREAD

**Issue by cogentcoder** [rkzofficial/ha-miraie-ac#17]
First of all thank you for providing this integration!

To fully utilize the potential of the ac and home assistant, I'd request adding following features.

- Many Panasonic ac have cool/hot mode but the integration does not provide to enable heat mode.
- Without separate entity for controlling on off, temperature, cool/hot modes, energy saving mode etc., the integration is not utilized for automation or scene task as none of those aspect can be changed. 
 
Thank you in advance!

**Comment by cogentcoder** [comment]
Update: the hot mode was present in the hidden menu in the 3 dots but in new update from July, it is not present. 
Can you please add the hot mode again?
Thank you!

**Comment by deCodeIt** [comment]
@cogentcoder Can you install the latest version (1.0.5) and share the logs when you do the following.

1. Turn off your ac from remote/app.
2. Wait ~5 seconds.
3. Turn on your ac from remote/app.
4. Wait ~5 seconds.
5. Set your ac on cool more.
6. Wait ~5 seconds.
7. Set your ac on heat mode.
8. Wait ~5 seconds.
9. Set your ac on min temp in heat mode ( if available )
10. wait ~5 seconds.
11. Set your ac on max temp in heat mode ( if available )
12. wait ~5 seconds.
13. Revert back to normal modes for your daily use.

Now after executing the above steps, do share the home assistant logs over here.

I'm interested in logs similar to
```
2024-08-03 16:16:05.860 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722681965', 'rssi': -36, 'ty': 'AC', 'ps': 'on', 'actmp': '29.0', 'acfs': 'high', 'acng': 'off', 'acngs': 'off', 'acvs': 0, 'achs': 0, 'acmd': 'cool', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '28.0', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130164', 'lcmd': 'actmp', 'sid': '1', 'cnt': 'an'}
```

**Comment by cogentcoder** [comment]
@deCodeIt I checked and updated to the latest version (2fc0de2) in the HACS but in the device integration miraie page, it shows  version number 1.0.4.

Enabled debug logging and did the suggested steps and got the following in the logs: 

`ValueError: Sensor sensor.panasonicac_on_time has device class 'None', state class 'None' unit 'time' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
2024-08-03 17:35:01.035 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

2024-08-03 17:36:07.296 DEBUG (MainThread) [custom_components.miraie] Set hvac mode to off
2024-08-03 17:36:07.434 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686766', 'rssi': -48, 'ty': 'AC', 'ps': 'off', 'actmp': '25.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'cool', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '27.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'ps', 'sid': '1', 'cnt': 'an'}
2024-08-03 17:36:07.434 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 25.0
Room temperature: 27.5
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.FOUR
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF

2024-08-03 17:38:45.242 DEBUG (MainThread) [custom_components.miraie] Set hvac mode to auto
2024-08-03 17:38:45.597 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686924', 'rssi': -48, 'ty': 'AC', 'ps': 'on', 'actmp': '24.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'auto', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '27.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'ps', 'sid': '1', 'cnt': 'an'}
2024-08-03 17:38:45.598 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 27.5
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.FOUR
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.AUTO
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF

2024-08-03 17:38:45.927 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686924', 'rssi': -48, 'ty': 'AC', 'ps': 'on', 'actmp': '24.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'auto', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '27.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'acmd', 'sid': '1', 'cnt': 'an'}
2024-08-03 17:38:45.927 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 27.5
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.FOUR
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.AUTO
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF

2024-08-03 17:38:57.553 DEBUG (MainThread) [custom_components.miraie] Set hvac mode to cool
2024-08-03 17:38:57.891 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686936', 'rssi': -47, 'ty': 'AC', 'ps': 'on', 'actmp': '24.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'cool', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '27.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'acmd', 'sid': '1', 'cnt': 'an'}
2024-08-03 17:38:57.892 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 27.5
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.FOUR
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF

2024-08-03 17:39:07.371 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686946', 'rssi': -48, 'ty': 'AC', 'ps': 'on', 'actmp': '24.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'cool', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '29.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'rmtmp', 'sid': 'aut_3', 'cnt': 'auto'}
2024-08-03 17:39:07.371 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 29.5
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.FOUR
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF

2024-08-03 17:39:17.690 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722686957', 'rssi': -48, 'ty': 'AC', 'ps': 'on', 'actmp': '24.0', 'acfs': 'auto', 'acng': 'off', 'acngs': 'off', 'acvs': 4, 'achs': 0, 'acmd': 'heat', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '29.5', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130149', 'lcmd': 'acmd', 'sid': 'rem_10', 'cnt': 'rem'}
2024-08-03 17:39:17.692 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/miraie_ac/broker.py", line 63, in connect
    self.on_message(message)
  File "/usr/local/lib/python3.12/site-packages/miraie_ac/broker.py", line 39, in on_message
    func(parsed)
  File "/usr/local/lib/python3.12/site-packages/miraie_ac/device.py", line 149, in status_handler
    hvac_mode=HVACMode(status["acmd"]),
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'heat' is not a valid HVACMode`

**Comment by deCodeIt** [comment]
@rkzofficial Can you add me as an admin / provide permissions to that I can merge to `main` branch without approvals and release python library for `mirarie-ac` as well as `ha-miraie-ac` repos? This will help speed up development of this package.

**Comment by deCodeIt** [comment]
> @rkzofficial Can you add me as an admin / provide permissions to that I can merge to `main` branch without approvals and release python library for `mirarie-ac` as well as `ha-miraie-ac` repos? This will help speed up development of this package.

@rkzofficial Can you do the needful?

**Comment by rkzofficial** [comment]
I have sent you the invite. @deCodeIt

**Comment by deCodeIt** [comment]
> I have sent you the invite. @deCodeIt

Received, I still lack the permission to release the PyPi package for miraie-ac lib via github actions. Can you check and allow me that perm
