### ISSUE TITLE
Preset modes not working for some models

### ISSUE THREAD

**Issue by maxakash** [rkzofficial/ha-miraie-ac#18]
Hi
Preset modes (eco, normal, powerful) don't work for some models( CS-CU-TU18YKY-1(1.5 TON)) .

Please look into it if get time.

Thanks

**Comment by deCodeIt** [comment]
@maxakash Can you install the latest version (1.0.5) and share the logs when you do the following.

Note: Do enable logs for this component by following the readme followed by restarting your HA instance and then execute the following steps.

1. Turn off your ac from remote.
2. Wait ~5 seconds.
3. Turn on your ac from remote.
4. Wait ~5 seconds.
5. Set your ac on cool mode from IR remote
6. Wait ~5 seconds.
7. Set your ac on eco mode from IR remote.
8. Wait ~5 seconds.
9. Set your ac on powerful mode from IR remote.
12. wait ~5 seconds.
13. Revert back to normal modes for your daily use.

Now after executing the above steps, do share the home assistant logs over here.

I'm interested in logs similar to
```
2024-08-03 16:16:05.860 DEBUG (MainThread) [custom_components.miraie] Raw device status: {'ts': '1722681965', 'rssi': -36, 'ty': 'AC', 'ps': 'on', 'actmp': '29.0', 'acfs': 'high', 'acng': 'off', 'acngs': 'off', 'acvs': 0, 'achs': 0, 'acmd': 'cool', 'acsp': 'none', 'acpm': 'off', 'acdc': 'on', 'acec': 'off', 'acem': 'off', 'acfc': 'off', 'actm': [-1, -1], 'acdl': 1, 'rmtmp': '28.0', 'acms': 'on', 'acmss': [1, 0, 0], 'acgm': 0, 'acpms': 0, 'cnv': 0, 'V': '2.15', 'mo': '130164', 'lcmd': 'actmp', 'sid': '1', 'cnt': 'an'}
```

**Comment by maxakash** [comment]
@deCodeIt Hi, I updated to  the latest version. Now I am getting the following error.
None of the ACs(7) are loaded.
Please look into this.

<img width="1291" alt="Screenshot 2024-08-03 at 6 07 05 PM" src="https://github.com/user-attachments/assets/b0b89bcd-7955-4112-8150-77b00ee6997a">

Here are the logs
```
2024-08-03 18:04:55.642 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-ZU24ZKYF
MAC address: aa:48:fa:d5:ea:23
Firmware version: 2.15
Serial number: 202303130531291809
Model number: CS-CU-ZU24ZKYF
Product serial number: 202303130531291809
2024-08-03 18:04:55.643 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:e9:7d:4f
Firmware version: 2.15
Serial number: 202301120908037917
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01441
2024-08-03 18:04:55.643 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18YKY-1
MAC address: 46:17:93:0a:5d:95
Firmware version: 1.75
Serial number: PZ20220406003132OU945
Model number: CS-CU-TU18YKY-1
Product serial number: 224PAJDPLU00113
2024-08-03 18:04:55.643 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-ZU24ZKYF
MAC address: 46:17:93:08:3d:df
Firmware version: 2.15
Serial number: 202303130529076929
Model number: CS-CU-ZU24ZKYF
Product serial number: 202303130529076929
2024-08-03 18:04:55.644 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:d1:5d:bf
Firmware version: 2.15
Serial number: 202301130626248963
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01076
2024-08-03 18:04:55.644 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:eb:f7:6d
Firmware version: 2.15
Serial number: 202301130508055568
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01055
2024-08-03 18:04:55.644 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:e2:e7:8a
Firmware version: 2.09
Serial number: 2023011306165044
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01070
2024-08-03 18:04:55.853 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 26.0
Room temperature: 28.0
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.ECO
Converti mode: ConvertiMode.OFF
2024-08-03 18:04:55.854 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - False
Temperature: 24.0
Room temperature: 26.5
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-03 18:04:55.854 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 26.0
Room temperature: 29.0
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-03 18:04:55.854 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 26.0
Room temperature: 30.5
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-03 18:04:55.854 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 31.0
Power mode: PowerMode.OFF
Fan mode: FanMode.MEDIUM
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-03 18:04:55.855 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - False
Temperature: 26.0
Room temperature: 29.5
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.AUTO
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
```

**Comment by deCodeIt** [comment]
@maxakash This is strange, can you completely remove the component via HACS and then reinstall to see if the same error occurs.

Also, do share the entire log file ( instead of copy-paste ) as it might contains errors missed during init.

**Comment by maxakash** [comment]
@deCodeIt I have tried multiple times, removed the ugin, reinstalled it, restarted. Eventually had to revert back to older version.

**Comment by deCodeIt** [comment]
Can you share the entire log file?

**Comment by deCodeIt** [comment]
Also, do you see any errors in `settings -> system -> logs` at the top? do share that screenshot too.

**Comment by maxakash** [comment]
> Also, do you see any errors in `settings -> system -> logs` at the top? do share that screenshot too.

No, it doesn't show any errors.
Just to be clear, I have only enabled critical logs and then debug logs for miraie plugin. 
Also the logs I shared before is the complete log file.
I am on latest version of HA.

**Comment by deCodeIt** [comment]
Can you have a log level of `info` for others and share the dump?

**Comment by maxakash** [comment]
@deCodeIt Here is the log file
```
2024-08-04 18:46:30.530 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-ZU24ZKYF
MAC address: aa:48:fa:d5:ea:23
Firmware version: 2.15
Serial number: 202303130531291809
Model number: CS-CU-ZU24ZKYF
Product serial number: 202303130531291809
2024-08-04 18:46:30.530 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:e9:7d:4f
Firmware version: 2.15
Serial number: 202301120908037917
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01441
2024-08-04 18:46:30.530 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18YKY-1
MAC address: 46:17:93:0a:5d:95
Firmware version: 1.75
Serial number: PZ20220406003132OU945
Model number: CS-CU-TU18YKY-1
Product serial number: 224PAJDPLU00113
2024-08-04 18:46:30.531 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-ZU24ZKYF
MAC address: 46:17:93:08:3d:df
Firmware version: 2.15
Serial number: 202303130529076929
Model number: CS-CU-ZU24ZKYF
Product serial number: 202303130529076929
2024-08-04 18:46:30.531 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:d1:5d:bf
Firmware version: 2.15
Serial number: 202301130626248963
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01076
2024-08-04 18:46:30.531 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:eb:f7:6d
Firmware version: 2.15
Serial number: 202301130508055568
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01055
2024-08-04 18:46:30.531 DEBUG (MainThread) [custom_components.miraie] Device details: Brand: PANASONIC
Category: AC
Model Name: PANASONIC AC
Model #: CS-CU-TU18ZKY-1
MAC address: b6:8a:0a:e2:e7:8a
Firmware version: 2.09
Serial number: 2023011306165044
Model number: CS-CU-TU18ZKY-1
Product serial number: 231PAJEDQU01070
2024-08-04 18:46:30.734 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 26.0
Room temperature: 27.0
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.ONE
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.ECO
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.734 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - False
Temperature: 24.0
Room temperature: 26.5
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.734 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 25.0
Room temperature: 26.5
Power mode: PowerMode.ON
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.ECO
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.735 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 26.0
Room temperature: 0.0
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.735 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - True
Temperature: 24.0
Room temperature: 0.0
Power mode: PowerMode.OFF
Fan mode: FanMode.MEDIUM
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.NONE
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.735 DEBUG (MainThread) [custom_components.miraie] Device status: Is online? - False
Temperature: 26.0
Room temperature: 29.0
Power mode: PowerMode.OFF
Fan mode: FanMode.AUTO
Vertical swing mode: SwingMode.AUTO
Horizontal swing mode: SwingMode.AUTO
Display mode: DisplayMode.ON
Hvac mode: HVACMode.COOL
Preset mode: PresetMode.ECO
Converti mode: ConvertiMode.OFF
2024-08-04 18:46:30.744 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MirAIe for miraie
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miraie/__init__.py", line 22, in async_setup_entry
await hub.init(entry.data["username"], entry.data["password"], broker)
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 37, in init
await self.get_all_device_status()
File "/usr/local/lib/python3.12/site-packages/miraie_ac/hub.py", line 217, in get_all_device_status
converti_mode=ConvertiMode(status["cnv"]),
~~~~~~^^^^^^^
KeyError: 'cnv'
```

**Comment by maxakash** [comment]
Here is the screenshot

<img width="1298" alt="Screenshot 2024-08-04 at 6 51 15 PM" src="https://github.com/user-attachments/assets/3e3c5f8e-b7f8-43f6-b298-85d05b432c7d">

**Comment by maxakash** [comment]
@deCodeIt It's working now. But now the value of swing mode is shown by default of Horizontal Swing. Earlier it was of Vertical Swing.
Also is there any way to turn on or off AC display?

**Comment by deCodeIt** [comment]
> @deCodeIt It's working now. But now the value of swing mode is shown by default of Horizontal Swing. Earlier it was of Vertical Swing. Also is there any way to turn on or off AC display?

With the support for horizontal swing released, you can refer to component readme for the display of swing modes.

Also, there's no inbuilt support in home assistant to toggle display mode. Maybe we can use a switch component for that but not a priority at the moment.

**Comment by deCodeIt** [comment]
@maxakash Display toggling switch has been added in v1.0.8

**Comment by maxakash** [comment]
> @maxakash Display toggling switch has been added in v1.0.8

Man! You are on fire. This was the feature I desperately needed. I had to open the app daily and turn it off.
