### ISSUE TITLE
Error setting up entry MirAIe for miraie

### ISSUE THREAD

**Issue by kp180-97** [rkzofficial/ha-miraie-ac#31]
Did the API integration change 

2024-12-26 01:48:47.427 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MirAIe for miraie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miraie/__init__.py", line 22, in async_setup_entry
    await hub.init(entry.data["username"], entry.data["password"], broker)
  File "/usr/local/lib/python3.13/site-packages/miraie_ac/hub.py", line 36, in init
    await self._get_home_details()
  File "/usr/local/lib/python3.13/site-packages/miraie_ac/hub.py", line 164, in _get_home_details
    await self._process_home_details(resp[0])
  File "/usr/local/lib/python3.13/site-packages/miraie_ac/hub.py", line 137, in _process_home_details
    device_details = await self._get_device_details(device_ids)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miraie_ac/hub.py", line 110, in _get_device_details
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1281, in json
    raise ContentTypeError(
    ...<7 lines>...
    )
aiohttp.client_exceptions.ContentTypeError: 404, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://app.miraie.in/simplifi/v1/deviceManagement/devices/deviceId/'

**Comment by deCodeIt** [comment]
I'm not sure why this error occurs but I would recommend you to simply **reload** our MirAIe component under `Devices & Services -> MirAIe -> <Click 3 dots> -> Reload` and it should start working.
It might be due to expiration of login token.

**Comment by kp180-97** [comment]
Tried to reload but still getting the same error

**Comment by deCodeIt** [comment]
I've added some logs that might help us figure out the issue here.

Request you to update to the latest version >= 1.0.12 for our ha-miraie-ac and dump the log file

**Comment by deCodeIt** [comment]
Stale for more than 30 days.
